# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = \
{'': 'python'}

packages = \
['lvmnps', 'lvmnps.actor', 'lvmnps.actor.commands', 'lvmnps.switch']

package_data = \
{'': ['*'], 'lvmnps': ['etc/*']}

install_requires = \
['click-default-group>=1.2.2,<2.0.0',
 'daemonocle>=1.1.1,<2.0.0',
 'dlipower>=1.0.176,<2.0.0',
 'sdss-access>=0.2.3',
 'sdss-clu>=1.0.3,<2.0.0',
 'sdss-tree>=2.15.2',
 'sdsstools>=0.4.0',
 'sphinx-bootstrap-theme>=0.7.1,<0.8.0']

extras_require = \
{'docs': ['Sphinx>=4.0.2,<5.0.0', 'sphinx_bootstrap_theme>=0.4.12']}

entry_points = \
{'console_scripts': ['npsactor = lvmnps.__main__:lvmnps']}

setup_kwargs = {
    'name': 'sdss-lvmnps',
    'version': '0.1.0a0',
    'description': 'Simple Template package for creating SDSS Python projects',
    'long_description': '# lvmnps\n\n![Versions](https://img.shields.io/badge/python->3.7-blue)\n[![Documentation Status](https://readthedocs.org/projects/sdss-lvmnps/badge/?version=latest)](https://sdss-lvmnps.readthedocs.io/en/latest/?badge=latest)\n[![Travis (.org)](https://img.shields.io/travis/sdss/lvmnps)](https://travis-ci.org/sdss/lvmnps)\n[![codecov](https://codecov.io/gh/sdss/lvmnps/branch/main/graph/badge.svg)](https://codecov.io/gh/sdss/lvmnps)\n\nSimple Template package for creating SDSS Python projects\n',
    'author': 'Changgon Kim',
    'author_email': 'changgonkim@khu.ac.kr',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/sdss/lvmnps',
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'extras_require': extras_require,
    'entry_points': entry_points,
    'python_requires': '>=3.7,<4.0',
}
from build import *
build(setup_kwargs)

setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
